### ISSUE TITLE
Executing Astor

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#83] opened 2018-04-30 11:53 UTC
Working with  Astor for the first time , on windows.
Trying to run the JGenprog ,and I get the below error?????

2018-05-01 23:05:25,143 INFO main - command line arguments: [-mode  jGenProg  -srcjavafolder  examples\Math-issue-280\src\java\  -srctestfolder  examples\Math-issue-280\src\test\  -binjavafolder  examples\Math-issue-280\target\classes\  -bintestfolder  examples\Math-issue-280\target\test-classes\  -location  astor\examples\Math-issue-280\  -dependencies  examples\Math-issue-280\lib]

fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:48) - Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:49)
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:22)
        at fr.inria.main.evolution.PlugInVisitor.loadCompiler(PlugInVisitor.java:187)
        at fr.inria.main.evolution.PlugInVisitor.load(PlugInVisitor.java:269)
        at fr.inria.astor.approaches.ingredientbased.IngredientBasedPlugInLoader.load(IngredientBasedPlugInLoader.java:133)
        at fr.inria.astor.core.loop.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1019)
        at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:122)
        at fr.inria.main.evolution.AstorMain.run(AstorMain.java:188)
        at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:245)
        at fr.inria.main.evolution.AstorMain.main(AstorMain.java:222)

**Comment by martinezmatias** [comment] 2018-05-02 09:04
Hi @ssk1216 
I have just committed a new test based on the command line you sent us.

**Closed by martinezmatias** 2018-05-02 09:04 UTC

**Comment by ssk1216** [comment] 2018-05-02 10:02
Thanks Martin.
But could u please tell me how to fix it ?
Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException

**Comment by martinezmatias** [comment] 2018-05-02 11:10
I wrote a new test case based on your command line.
It does not throw an exception, at least on MacOs and Linux
https://github.com/SpoonLabs/astor/commit/973c09bad693096933a614a72df57d16af9125eb

**Comment by leena268** [comment] 2020-03-27 06:05
Hi Martinez, I am facing the same error . Can you please let me know how to fix it ..

[ERROR] fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:48) - Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:49)
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:22)
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadCompiler(AstorCoreEngine.java:1109)
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1306)
        at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:109)
        at fr.inria.main.evolution.AstorMain.run(AstorMain.java:169)
        at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:229)
        at fr.inria.main.evolution.AstorMain.main(AstorMain.java:200)

**Comment by leena268** [comment] 2020-03-27 06:05
I have tried everything possible you have suggested above + looked into your test too ...

**Comment by martinezmatias** [comment] 2020-03-27 06:46
Hi @leena268 
Could you send me the command line you are executing?
Thanks
Matias

**Comment by leena268** [comment] 2020-03-27 16:19
Hi Matias,  Thanks for your response . Here you go . I am now trying to log the flow and trying to understand where the issue is 
Command : 
java-cp target/astor-1.0.0-SNAPSHOT-jar-with-dependencies.jarfr.inria.main.evolution.AstorMain -mode jKali -locationD:/MELCourse/SoftwareVerification/Presentation/AstorV2/astor/examples/math_70 -modejKali -package  org.apache.commons -failingorg.apache.commons.math.analysis.solvers.BisectionSolverTest -srcjavafolder/src/java/ -binjavafolder /target/classes -srctestfolder /src/test -bintestfolder/target/test-classes -flthreshold 0.5 -stopfirst true -dependenciesD:/MELCourse/SoftwareVerification/Presentation/AstorV2/astor/examples/libs/junit-4.4.jar 
Error[ERROR] fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:53) - Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerExceptionException in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:54)        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:25)        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadCompiler(AstorCoreEngine.java:1109)        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1306)        at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:113)        at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)        at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)        at fr.inria.main.evolution.AstorMain.main(AstorMain.java:204)



ThanksLeena
    On Thursday, March 26, 2020, 11:46:36 PM PDT, Matias Martinez <notifications@github.com> wrote:  
 
 


Hi @leena268
Could you send me the command line you are executing?
Thanks
Matias

**Comment by martinezmatias** [comment] 2020-03-27 17:39
Hi @leena268 
-locationD:/MELCourse/SoftwareVerification/
In the command line you copied is missing a space: -location D:/MELCourse/SoftwareVerification/
Could you check if that space is also missing in your command line?

**Comment by leena268** [comment] 2020-03-27 17:56
Hi Matias,    No :( . Might have been a typo when i put it in the mail . Here is the snapshot of my cmd window. 

When does this error occur. Am i doing anything wrong in the creation of jar file. I even tried target/* for the -cp option as captured below. To create the jar i have used the mvn package call 
ThanksLeena



j

    On Friday, March 27, 2020, 10:39:31 AM PDT, Matias Martinez <notifications@github.com> wrote:  
 
 


Hi @leena268
-locationD:/MELCourse/SoftwareVerification/
In the command line you copied is missing a space: -location D:/MELCourse/SoftwareVerification/
Could you check if that space is also missing in your command line?

**Comment by martinezmatias** [comment] 2020-03-31 11:53
Hi @leena268 

Could you try to put the absolute path to the Jar in the cp argument?

e.g. java -cp /home/myfolder/astor/target/astor-1.0.0-SNAPSHOT-jar-with-dependencies.jar
